name: Update YouTube Channel Markdown

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at 00:00

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytube pymdown-extensions

    - name: Run update
      run: python update.py  # Replace with your script's path

    - name: Commit and push if it's not a pull request
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git commit -am "Update YouTube Channel Markdown" -a
        git push